import { expect, test, type Page } from '@playwright/test'

async function navigate(page: Page, view: 'Mapa' | 'Navios') {
  if (await page.getByRole('button', { name: 'Abrir menu' }).isVisible()) {
    await page.getByRole('button', { name: 'Abrir menu' }).click()
    const drawer = page.getByRole('dialog', { name: 'Menu de navegação' })
    await expect(drawer).toBeVisible()
    await drawer.getByRole('button', { name: view, exact: true }).click()
    await expect(drawer).not.toBeVisible()
  } else {
    await page.locator('.desktop-sidebar').getByRole('button', { name: view, exact: true }).click()
  }
}

async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(await page.locator('.main-content').evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
}

test('mapa real, temas, navegação, CRUD sincronizado e layout responsivo', async ({ page }, testInfo) => {
  const runtimeErrors: string[] = []
  page.on('pageerror', error => runtimeErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Mapa da frota' })).toBeVisible()
  await expect(page.locator('.ship-map-icon')).toHaveCount(3)
  await noOverflow(page)
  await expect.poll(() => page.locator('.leaflet-tile').evaluateAll(images => images.filter(image => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0).length), { timeout: 20000 }).toBeGreaterThan(0)
  await expect(page.getByRole('link', { name: 'OpenStreetMap', exact: true })).toBeVisible()

  const mainBox = await page.locator('.main-content').boundingBox()
  const themeBox = await page.locator('.theme-toggle').boundingBox()
  expect(mainBox && themeBox && mainBox.y + mainBox.height <= themeBox.y).toBeTruthy()

  await page.screenshot({ path: testInfo.outputPath('mapa-dark.png') })
  await page.getByRole('button', { name: 'Ativar tema claro' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.screenshot({ path: testInfo.outputPath('mapa-light.png') })
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')

  const zoom = page.locator('.map-zoom-level')
  await expect(zoom).toBeVisible()
  const initialZoom = Number((await zoom.textContent())?.replace('Zoom ', ''))
  await page.getByRole('button', { name: 'Aproximar mapa' }).click()
  await expect(zoom).toHaveText('Zoom ' + (initialZoom + 1))
  await page.getByRole('button', { name: 'Afastar mapa' }).click()
  await expect(zoom).toHaveText('Zoom ' + initialZoom)

  const pane = page.locator('.leaflet-map-pane')
  const oldTransform = await pane.getAttribute('style')
  const mapBox = await page.locator('.fleet-map').boundingBox()
  if (!mapBox) throw new Error('Mapa sem área visível.')
  await page.mouse.move(mapBox.x + mapBox.width * .3, mapBox.y + mapBox.height * .5)
  await page.mouse.down()
  await page.mouse.move(mapBox.x + mapBox.width * .3 + 65, mapBox.y + mapBox.height * .5 + 35, { steps: 8 })
  await page.mouse.up()
  await expect.poll(() => pane.getAttribute('style')).not.toEqual(oldTransform)
  await page.getByRole('button', { name: 'Brasil', exact: true }).click()
  await page.getByRole('button', { name: 'Ver frota' }).click()
  await page.getByTitle('Atlântico', { exact: true }).click()
  await expect(page.locator('.ship-popup')).toContainText('Atlântico')
  await expect(page.locator('.ship-popup')).toContainText('-8,2300')
  await page.locator('.leaflet-popup-close-button').click()
  await page.getByRole('button', { name: 'Localizar Atlântico' }).click()
  await expect(page.locator('.ship-popup')).toContainText('Atlântico')
  await page.locator('.leaflet-popup-close-button').click()
  await page.getByRole('button', { name: 'Localizar Atlântico' }).click()
  await expect(page.locator('.ship-popup')).toContainText('Atlântico')

  if (await page.getByRole('button', { name: 'Abrir menu' }).isVisible()) {
    await page.getByRole('button', { name: 'Abrir menu' }).click()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog', { name: 'Menu de navegação' })).not.toBeVisible()
  }
  await navigate(page, 'Navios')
  await expect(page.getByRole('heading', { name: 'Seus navios' })).toBeVisible()
  await noOverflow(page)
  await page.getByRole('button', { name: 'Novo navio', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Novo navio', exact: true })
  await dialog.getByRole('button', { name: 'Salvar navio' }).click()
  await expect(dialog.getByText('Informe o nome do navio.')).toBeVisible()
  await expect(dialog.getByLabel('Nome do navio')).toBeFocused()
  await dialog.getByLabel('Nome do navio').fill('Teste Litoral')
  await dialog.getByLabel('Latitude', { exact: true }).fill('91')
  await dialog.getByLabel('Longitude', { exact: true }).fill('181')
  await dialog.getByRole('button', { name: 'Salvar navio' }).click()
  await expect(dialog.getByText('Informe uma latitude entre -90 e 90.')).toBeVisible()
  await expect(dialog.getByText('Informe uma longitude entre -180 e 180.')).toBeVisible()
  await dialog.getByLabel('Latitude', { exact: true }).fill('-13,5000')
  await dialog.getByLabel('Longitude', { exact: true }).fill('-38.2000')
  await expect(dialog.locator('.field-error')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('formulario.png') })
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await dialog.getByRole('button', { name: 'Salvar navio' }).click()
  await expect(dialog).not.toBeVisible()
  let row = page.getByRole('row').filter({ hasText: 'Teste Litoral' })
  await expect(row).toContainText('-13,5000')
  await noOverflow(page)
  await navigate(page, 'Mapa')
  await expect(page.locator('.ship-map-icon')).toHaveCount(4)
  await page.getByRole('button', { name: 'Localizar Teste Litoral' }).click()
  await expect(page.locator('.ship-popup')).toContainText('-38,2000')

  await navigate(page, 'Navios')
  await page.getByRole('button', { name: 'Editar Teste Litoral' }).click()
  dialog = page.getByRole('dialog', { name: 'Editar navio', exact: true })
  await dialog.getByLabel('Nome do navio').fill('Navio Revisado')
  await dialog.getByLabel('Latitude', { exact: true }).fill('-12.75')
  await dialog.getByLabel('Longitude', { exact: true }).fill('-38,45')
  await dialog.getByRole('button', { name: 'Salvar navio' }).click()
  row = page.getByRole('row').filter({ hasText: 'Navio Revisado' })
  await expect(row).toContainText('-12,7500')
  await page.screenshot({ path: testInfo.outputPath('navios-light.png') })
  await page.getByRole('button', { name: 'Ativar tema escuro' }).click()
  await page.screenshot({ path: testInfo.outputPath('navios-dark.png') })
  await navigate(page, 'Mapa')
  await page.getByRole('button', { name: 'Localizar Navio Revisado' }).click()
  await expect(page.locator('.ship-popup')).toContainText('-12,7500')
  await expect(page.locator('.ship-popup')).toContainText('-38,4500')
  await expect(page.getByRole('button', { name: 'Localizar Teste Litoral' })).toHaveCount(0)
  await navigate(page, 'Navios')
  await page.getByRole('button', { name: 'Excluir Navio Revisado' }).click()
  const deletion = page.getByRole('dialog', { name: 'Excluir navio', exact: true })
  await deletion.getByRole('button', { name: 'Cancelar', exact: true }).click()
  await expect(row).toBeVisible()
  await page.getByRole('button', { name: 'Excluir Navio Revisado' }).click()
  await deletion.getByRole('button', { name: 'Excluir navio', exact: true }).click()
  await expect(row).toHaveCount(0)
  await navigate(page, 'Mapa')
  await expect(page.locator('.ship-map-icon')).toHaveCount(3)
  await expect(page.getByRole('button', { name: 'Localizar Navio Revisado' })).toHaveCount(0)

  await navigate(page, 'Navios')
  for (const name of ['Atlântico', 'Aurora', 'Horizonte']) {
    await page.getByRole('button', { name: 'Excluir ' + name }).click()
    await deletion.getByRole('button', { name: 'Excluir navio', exact: true }).click()
  }
  await expect(page.getByRole('heading', { name: 'Nenhum navio cadastrado' })).toBeVisible()
  await navigate(page, 'Mapa')
  await expect(page.locator('.ship-map-icon')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Ver frota' })).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Sua frota começa aqui' })).toBeVisible()
  await page.reload()
  await expect(page.locator('.ship-map-icon')).toHaveCount(3)
  expect(runtimeErrors).toEqual([])
})
